In [4]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [6]:
ar

array([1, 2, 3, 4])

In [7]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
a = [2,3,4]

In [11]:
np.asanyarray(a)

array([2, 3, 4])

In [12]:
b = np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c = a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
a

array([1, 2, 3, 4])

In [21]:
c[0] 

1

In [22]:
c[0] = 100

In [23]:
c

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
d = np.copy(a)

In [26]:
d

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [29]:
a[1] = 400

In [30]:
a

array([100, 400,   3,   4])

In [31]:
d

array([100,   2,   3,   4])

In [32]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable = (i*i for i in range(5))

In [35]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [36]:
np.fromstring('234 234', sep=' ')

array([234., 234.])

In [37]:
np.fromstring('4,5', sep=',')

array([4., 5.])

In [38]:
# Numpy - Data Types:

In [39]:
l = [2,3,4,5,6]

In [40]:
ar = np.array(l)

In [41]:
ar

array([2, 3, 4, 5, 6])

In [42]:
ar.ndim

1

In [43]:
ar2 = np.array([[1,2,3,4], [2,3,4,5]])

In [44]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [45]:
ar2.ndim

2

In [46]:
ar.size

5

In [47]:
ar2.size

8

In [48]:
ar

array([2, 3, 4, 5, 6])

In [49]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [50]:
ar.shape

(5,)

In [51]:
ar2.shape

(2, 4)

In [52]:
ar.dtype

dtype('int64')

In [53]:
ar2.dtype

dtype('int64')

In [54]:
ar22 = np.array([(1.4,45,45), (23,45,66)])

In [55]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [56]:
ar22.dtype

dtype('float64')

In [57]:
list(range(5))

[0, 1, 2, 3, 4]

In [58]:
list(range(.1, 5))

TypeError: 'float' object cannot be interpreted as an integer

In [59]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [60]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [62]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [63]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [4]:
ar4 = np.zeros((3,4,2,3))

In [5]:
ar4.ndim

4

In [6]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
on = np.ones((2,3,2))

In [11]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [12]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [16]:
np.empty((3,6))

array([[4.66812855e-310, 0.00000000e+000, 6.94021369e-310,
        6.94021479e-310, 6.94021477e-310, 6.94021369e-310],
       [6.94021369e-310, 6.94021367e-310, 6.94021369e-310,
        6.94021477e-310, 6.94021368e-310, 6.94021368e-310],
       [6.94021369e-310, 6.94021477e-310, 6.94021369e-310,
        6.94021369e-310, 6.94021455e-310, 6.94021479e-310]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [20]:
np.logspace(2,5, 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [5]:
arr = np.random.randn(3,4)

In [6]:
import pandas as pd

In [7]:
pd.DataFrame(arr)

0         1         2         3
0  0.500538 -0.870119 -1.544419 -1.821465
1 -1.634638  1.095965 -1.159668  0.968811
2  0.205297 -0.204577 -0.077343 -0.687024

In [8]:
np.random.rand(3,4)

array([[0.40871313, 0.96729067, 0.02128212, 0.61472131],
       [0.9044024 , 0.44097015, 0.50871929, 0.97087743],
       [0.50049386, 0.73608303, 0.53340961, 0.37224136]])

In [48]:
pd.DataFrame(np.random.randint(1,110, (300,400))).to_csv('test.csv')

In [9]:
arr = np.random.rand(3,4)

In [10]:
arr

array([[0.90107076, 0.30936945, 0.67935957, 0.34542991],
       [0.2710974 , 0.37843892, 0.32037773, 0.27573847],
       [0.58002517, 0.72503938, 0.78907619, 0.24145703]])

In [11]:
arr.reshape(6,2)

array([[0.90107076, 0.30936945],
       [0.67935957, 0.34542991],
       [0.2710974 , 0.37843892],
       [0.32037773, 0.27573847],
       [0.58002517, 0.72503938],
       [0.78907619, 0.24145703]])

In [12]:
arr1 = arr.reshape(6,-132445)

In [13]:
arr1

array([[0.90107076, 0.30936945],
       [0.67935957, 0.34542991],
       [0.2710974 , 0.37843892],
       [0.32037773, 0.27573847],
       [0.58002517, 0.72503938],
       [0.78907619, 0.24145703]])

In [14]:
arr1[1][1]

0.34542990954715025

In [15]:
arr1[2:5,1]

array([0.37843892, 0.27573847, 0.72503938])

In [20]:
arr5 = np.random.randint(1,100, (5,5))

In [21]:
arr5

array([[36, 92,  2, 78, 22],
       [90, 94, 63, 62, 49],
       [80, 54, 72, 29, 27],
       [74, 32,  8,  8, 48],
       [77, 67, 47, 44, 50]])

In [22]:
arr5>50

array([[False,  True, False,  True, False],
       [ True,  True,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False]])

In [23]:
arr[arr5>50]

array([34, 82, 49, 78, 84, 47, 51, 47, 99, 67,  5,  1])

In [24]:
arr5

array([[36, 92,  2, 78, 22],
       [90, 94, 63, 62, 49],
       [80, 54, 72, 29, 27],
       [74, 32,  8,  8, 48],
       [77, 67, 47, 44, 50]])

In [25]:
arr5[2:4, [1,2]]

array([[54, 72],
       [32,  8]])

In [27]:
arr5[0][0] = 5000

In [28]:
arr5

array([[5000,   92,    2,   78,   22],
       [  90,   94,   63,   62,   49],
       [  80,   54,   72,   29,   27],
       [  74,   32,    8,    8,   48],
       [  77,   67,   47,   44,   50]])

In [30]:
arr3 = np.random.randint(1,3, (3,3))
arr4 = np.random.randint(1,3, (3,3))

In [31]:
arr3

array([[1, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [32]:
arr4

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [33]:
arr3 + arr4

array([[2, 3, 3],
       [4, 3, 3],
       [2, 2, 2]])

In [34]:
arr3 - arr4

array([[ 0,  1,  1],
       [ 0, -1, -1],
       [ 0,  0,  0]])

In [35]:
arr3 / arr4

array([[1. , 2. , 2. ],
       [1. , 0.5, 0.5],
       [1. , 1. , 1. ]])

In [37]:
arr3 * arr4  # not provide matrix multiplication

array([[1, 2, 2],
       [4, 2, 2],
       [1, 1, 1]])

In [39]:
arr3@arr4  # provide matrix multiplication

array([[7, 7, 7],
       [5, 5, 5],
       [4, 4, 4]])

In [40]:
arr3/0

/tmp/ipykernel_77/1466893960.py:1: RuntimeWarning: divide by zero encountered in divide
  arr3/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [41]:
arr3 + 100

array([[101, 102, 102],
       [102, 101, 101],
       [101, 101, 101]])

In [42]:
arr3 ** 2

array([[1, 4, 4],
       [4, 1, 1],
       [1, 1, 1]])

In [43]:
# Numpy - Broadcasting 

In [45]:
arr6 = np.zeros((4,4))

In [46]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
row = np.array([1,2,3,4])

In [49]:
row

array([1, 2, 3, 4])

In [50]:
arr6 + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [51]:
row.shape

(4,)

In [54]:
row.ndim

1

In [55]:
row.T

array([1, 2, 3, 4])

In [56]:
col = np.array([[1,2,3,4]])

In [57]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [58]:
col

array([[1, 2, 3, 4]])

In [59]:
col.T + arr6

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [60]:
arr7 = np.random.randint(1,4, (3,4))

In [61]:
arr7

array([[1, 1, 1, 1],
       [1, 3, 3, 3],
       [3, 1, 3, 3]])

In [62]:
np.sqrt(arr7)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.        , 1.73205081, 1.73205081]])

In [63]:
np.exp(arr7)

array([[ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [ 2.71828183, 20.08553692, 20.08553692, 20.08553692],
       [20.08553692,  2.71828183, 20.08553692, 20.08553692]])

In [64]:
np.log10(arr7)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.47712125, 0.47712125, 0.47712125],
       [0.47712125, 0.        , 0.47712125, 0.47712125]])