In [1]:
# Numpy - Array Manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10, (3,4))

In [4]:
arr

array([[9, 5, 9, 4],
       [9, 1, 9, 5],
       [2, 7, 4, 1]])

In [5]:
arr.reshape(6,2)

array([[9, 5],
       [9, 4],
       [9, 1],
       [9, 5],
       [2, 7],
       [4, 1]])

In [6]:
arr.reshape(2,6)

array([[9, 5, 9, 4, 9, 1],
       [9, 5, 2, 7, 4, 1]])

In [7]:
arr.reshape(2,-3435)

array([[9, 5, 9, 4, 9, 1],
       [9, 5, 2, 7, 4, 1]])

In [8]:
arr.T

array([[9, 9, 2],
       [5, 1, 7],
       [9, 9, 4],
       [4, 5, 1]])

In [9]:
arr

array([[9, 5, 9, 4],
       [9, 1, 9, 5],
       [2, 7, 4, 1]])

In [11]:
arr.flatten()  # change into in one dimention

array([9, 5, 9, 4, 9, 1, 9, 5, 2, 7, 4, 1])

In [12]:
arr1 = np.array([1,2,3,4])

In [13]:
arr1.ndim

1

In [14]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [15]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4]])

In [16]:
arr

array([[9, 5, 9, 4],
       [9, 1, 9, 5],
       [2, 7, 4, 1]])

In [17]:
np.squeeze(arr)

array([[9, 5, 9, 4],
       [9, 1, 9, 5],
       [2, 7, 4, 1]])

In [18]:
data = np.array([[1], [2], [3]])

In [19]:
data

array([[1],
       [2],
       [3]])

In [20]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
arr1

array([1, 2, 3, 4])

In [22]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [23]:
np.roll(arr1, 2)

array([3, 4, 1, 2])

In [24]:
arr1

array([1, 2, 3, 4])

In [25]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
# Numpy - Binary Operators.

In [27]:
arr2 = np.random.randint(1,10, (3,4))

In [28]:
arr3 = np.random.randint(1,10, (3,4))

In [29]:
arr2

array([[5, 3, 1, 6],
       [5, 6, 8, 7],
       [8, 6, 8, 4]])

In [30]:
arr3

array([[4, 9, 8, 8],
       [6, 5, 9, 6],
       [6, 2, 2, 6]])

In [31]:
arr2 + arr3

array([[ 9, 12,  9, 14],
       [11, 11, 17, 13],
       [14,  8, 10, 10]])

In [32]:
arr2 * arr3

array([[20, 27,  8, 48],
       [30, 30, 72, 42],
       [48, 12, 16, 24]])

In [34]:
arr2/arr3

array([[1.25      , 0.33333333, 0.125     , 0.75      ],
       [0.83333333, 1.2       , 0.88888889, 1.16666667],
       [1.33333333, 3.        , 4.        , 0.66666667]])

In [35]:
arr2-arr3

array([[ 1, -6, -7, -2],
       [-1,  1, -1,  1],
       [ 2,  4,  6, -2]])

In [36]:
arr2%arr3

array([[1, 3, 1, 6],
       [5, 1, 8, 1],
       [2, 0, 0, 4]])

In [37]:
arr2 ** arr3

array([[      625,     19683,         1,   1679616],
       [    15625,      7776, 134217728,    117649],
       [   262144,        36,        64,      4096]])

In [38]:
arr2 & arr3

array([[4, 1, 0, 0],
       [4, 4, 8, 6],
       [0, 2, 0, 4]])

In [39]:
arr2

array([[5, 3, 1, 6],
       [5, 6, 8, 7],
       [8, 6, 8, 4]])

In [40]:
arr3

array([[4, 9, 8, 8],
       [6, 5, 9, 6],
       [6, 2, 2, 6]])

In [41]:
~arr2

array([[-6, -4, -2, -7],
       [-6, -7, -9, -8],
       [-9, -7, -9, -5]])

In [42]:
arr2|arr3

array([[ 5, 11,  9, 14],
       [ 7,  7,  9,  7],
       [14,  6, 10,  6]])

In [43]:
arr2>arr3

array([[ True, False, False, False],
       [False,  True, False,  True],
       [ True,  True,  True, False]])

In [44]:
# Numpy - String Functions.

In [45]:
arr4 = np.array(['sudh', 'kumar'])

In [46]:
arr4

array(['sudh', 'kumar'], dtype='<U5')

In [47]:
np.char.upper(arr4)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [48]:
np.char.capitalize(arr4)

array(['Sudh', 'Kumar'], dtype='<U5')

In [49]:
np.char.title(arr4)

array(['Sudh', 'Kumar'], dtype='<U5')

In [50]:
# Numpy - Mathematical Functions.

In [53]:
arr2

array([[5, 3, 1, 6],
       [5, 6, 8, 7],
       [8, 6, 8, 4]])

In [54]:
np.sin(arr2)

array([[-0.95892427,  0.14112001,  0.84147098, -0.2794155 ],
       [-0.95892427, -0.2794155 ,  0.98935825,  0.6569866 ],
       [ 0.98935825, -0.2794155 ,  0.98935825, -0.7568025 ]])

In [55]:
np.cos(arr2)

array([[ 0.28366219, -0.9899925 ,  0.54030231,  0.96017029],
       [ 0.28366219,  0.96017029, -0.14550003,  0.75390225],
       [-0.14550003,  0.96017029, -0.14550003, -0.65364362]])

In [56]:
np.tan(arr2)

array([[-3.38051501, -0.14254654,  1.55740772, -0.29100619],
       [-3.38051501, -0.29100619, -6.79971146,  0.87144798],
       [-6.79971146, -0.29100619, -6.79971146,  1.15782128]])

In [57]:
np.tanh(arr2)

array([[0.9999092 , 0.99505475, 0.76159416, 0.99998771],
       [0.9999092 , 0.99998771, 0.99999977, 0.99999834],
       [0.99999977, 0.99998771, 0.99999977, 0.9993293 ]])

In [58]:
np.log10(arr2)

array([[0.69897   , 0.47712125, 0.        , 0.77815125],
       [0.69897   , 0.77815125, 0.90308999, 0.84509804],
       [0.90308999, 0.77815125, 0.90308999, 0.60205999]])

In [59]:
np.exp(arr2)

array([[1.48413159e+02, 2.00855369e+01, 2.71828183e+00, 4.03428793e+02],
       [1.48413159e+02, 4.03428793e+02, 2.98095799e+03, 1.09663316e+03],
       [2.98095799e+03, 4.03428793e+02, 2.98095799e+03, 5.45981500e+01]])

In [60]:
np.sqrt(arr2)

array([[2.23606798, 1.73205081, 1.        , 2.44948974],
       [2.23606798, 2.44948974, 2.82842712, 2.64575131],
       [2.82842712, 2.44948974, 2.82842712, 2.        ]])

In [61]:
np.power(arr2, 2)

array([[25,  9,  1, 36],
       [25, 36, 64, 49],
       [64, 36, 64, 16]])

In [62]:
np.mean(arr2)

5.583333333333333

In [63]:
np.median(arr2)

6.0

In [64]:
np.std(arr2)

2.0598678490513795

In [65]:
np.var(arr2)

4.243055555555556

In [66]:
np.min(arr2)

1

In [67]:
np.max(arr2)

8